## Урок 8

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: <br>
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. <br>
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. <br>
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [36]:
import numpy as np
from scipy import stats

In [37]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [38]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [39]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [10]:
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Правильно ли я поняла, что выводы мы здесь можем сделать следующие: <br>
    1. C достоверностью 95% можно утверждать, что рост спортсменов зависит от вида спорта <br>
    2. А с достоверностью 99% можно утверждать, что рост спортсменов не зависит от вида спорта? <br>
Так? Я не понимаю логики... Может быть, я что-то не поняла? Как можно сделать два взаимоисключающих вывода? Может быть правильный вывод - что нет связи между ростом спортсменов и этими видами спорта?


Попробую посчитать вручную:

$$\overline{y}_{i} = \frac{1}{n_i}\sum\limits_{j=1}^{n_i}y_{ij}$$

In [40]:
n1 = len(y1)
n1

8

In [41]:
n2 = len(y2)
n2

9

In [42]:
n3 = len(y3)
n3

11

In [65]:
Y1 = sum(y1) / n1
Y1

179.125

In [66]:
Y2 = sum(y2) / n2
Y2

178.66666666666666

In [67]:
Y3 = sum(y3) / n3
Y3

172.72727272727272

$$\overline{Y} = \frac{1}{n}\sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}y_{ij} = \frac{1}{n}\sum\limits_{i=1}^{k}\overline{y}_{i}n_{i}$$

In [64]:
k = n1 + n2 + n3
k

28

In [68]:
Y = (Y1*n1 + Y2*n2 + Y3*n3) / k
Y

176.46428571428572

$$S^2 = \sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}({y}_{ij} - \overline{Y})^2$$

In [75]:
s1 = []
for i in y1:
    s1 = (y1 - Y)**2
s1 = sum(s1)
s1

175.5102040816323

In [76]:
s2 = []
for i in y2:
    s2 = (y2 - Y)**2
s2 = sum(s2)
s2

271.6543367346936

In [77]:
s3 = []
for i in y3:
    s3 = (y3 - Y)**2
s3 = sum(s3)
s3

383.7997448979599

In [78]:
S2 = s1 + s2 + s3
S2

830.9642857142858

$$S_F^2 = \sum\limits_{i=1}^{k}(\overline{y}_i - \overline{Y})^2n_i$$

In [79]:
S2F = (Y1 - Y)**2 * n1 + (Y2 - Y)**2 * n2 + (Y3 - Y)**2 * n3
S2F

253.9074675324678

$$S_{ост}^{2} = \sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}(y_{ij} - \overline{y}_i)^2$$

In [80]:
S2OST = S2 - S2F
S2OST

577.056818181818

$$\sigma_{общ}^{2} = \frac{S^2}{n - 1} = \frac{1}{n-1}\sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}(y_{ij} - \overline{Y})^2$$

In [81]:
Dtot = S2 / (n1 + n2 + n3 - 1)
Dtot

30.77645502645503

$$\sigma_{F}^{2} = \frac{S_{F}^{2}}{k-1} = \frac{1}{k-1}\sum\limits_{i=1}^{k}(\overline{y}_i - \overline{Y})^{2}n_i$$

In [82]:
DF = S2F / (3 - 1)
DF

126.9537337662339

$$\sigma_{ост}^{2} = \frac{S_{ост}^{2}}{n - k} = \frac{1}{n - k}\sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}(y_{ij} - \overline{y}_i)^2$$

In [83]:
DOST = S2OST / (n1 + n2 + n3 - 3)
DOST

23.08227272727272

In [84]:
FH = DF / DOST
FH

5.5000534508126

<b>Ftab (2/25) = 3.39 (при а = 5%)

FH < Ftab, значит средний рост в трех видах спорта, который мы рассматриваем - не отличается.

<b>Ftab (2/25) = 5.57 (при а = 1%)

FH > Ftab, значит средний рост в трех видах спорта, который мы рассматриваем - отличается.