## Урок 6

### Задача 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].<br>

In [15]:
import numpy as np

In [16]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [18]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.<br>

$$cov_{XY} = M(XY) - M(X)M(Y)$$

In [29]:
cov = (zp*ks).mean() - zp.mean()*ks.mean()
cov

9157.839999999997

In [34]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

$$r_{XY} = \frac{cov_{XY}}{\sigma_{X}\sigma_{Y}}$$

In [35]:
cov/(zp.std()*ks.std())

0.8874900920739158

In [19]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Или:

In [38]:
np.cov(zp, ks)/(zp.std(ddof=1)*ks.std(ddof=1))

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

### Задача 2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

Поскольку мы не знаем std гс, то доверительный интервал будем считать по формулам: $ X - t_{a/2} * \frac{Std}{\sqrt{n}}$ и $ X + t_{a/2} * \frac{Std}{\sqrt{n}}$

In [8]:
import numpy as np
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
X = x.mean()
X

118.1

In [10]:
std = x.std(ddof=1)
std

10.54566788359614

In [11]:
X - 2.262 * std / (10 ** (1/2))

110.55660776308164

In [12]:
X + 2.262 * std / (10 ** (1/2))

125.64339223691834

In [13]:
[110.56, 125.64]

[110.56, 125.64]

### Задача 3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежность 0,95

Доверительный интервал считаем по формулам: $ X - Z_{a/2} * \frac{Std}{\sqrt{n}}$ и $ X + Z_{a/2} * \frac{Std}{\sqrt{n}}$

In [2]:
174.2 - 1.96 * (25**(1/2))/(27**(1/2))

172.31398912064722

In [3]:
174.2 + 1.96 * (25**(1/2))/(27**(1/2))

176.08601087935276

In [4]:
[172.31, 176.09]

[172.31, 176.09]